config/routes.rb
Rails.application.routes.draw do
  resources :points

  root 'points#index'

end

app/models/point.rb
class Point
  include Mongoid::Document
  include Mongoid::Paranoia
  include Mongoid::Timestamps
  include Geocoder::Model::Mongoid
  
  field :coordinates, type: Array    # [E, N] [longitude, latitude] --> 9.822864, 51.650772
  field :address
  #belongs_to :type

  validates :address, :coordinates, presence: true
  
  index({ coordinates: '2d' }, { min: -180, max: 180 })
  
  geocoded_by :address
  
  reverse_geocoded_by :coordinates
    
  before_validation :geocode_all
  
  
  def latitude
    # TODO: TEST
    # TODO: YARD
    coordinates[1]
  end

  def longitude
    # TODO: TEST
    # TODO: YARD
    coordinates[0]
  end
  
  
  def geocode_all
    # TODO: TEST
    # TODO: YARD
    if address.present? && coordinates.blank?
      geocode
    elsif address.blank? && coordinates.present?
      reverse_geocode
    end
  end
  
  private
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  # GET /points
  # GET /points.json
  def index
    #@points = Point.all
    @points =
      [
        { id: 1, coordinates: [9.822864, 51.650772] },
        { id: 2, coordinates: [9.823722, 51.648788] },
        { id: 3, coordinates: [9.835953, 51.648482] },
        { id: 4, coordinates: [9.797286, 51.668196] },
        { id: 5, coordinates: [9.883331, 51.633408] },
        { id: 6, coordinates: [9.936804, 51.614452] },
        { id: 7, coordinates: [9.944529, 51.738370] },
        { id: 8, coordinates: [9.907965, 51.802544] },
        { id: 9, coordinates: [9.882345, 51.813224] },
        { id: 10, coordinates: [10.615176, 51.799782] }
      ]
    @markers = Gmaps4rails.build_markers(@points) do |point, marker|
      marker.title        'title'
      marker.infowindow   'description'
      marker.lat point[:coordinates][1]
      # marker.lat point.latitude
      marker.lng point[:coordinates][0]
#      marker.lng point.longitude
##      marker.json({:id => point.id })
##      marker.picture({
##        "url" => "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
##        "width" =>  32,
##        "height" => 32}
##      )
    end.to_json
#    @markers = [].to_json
    @map_options = generate_map_options.to_json
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)

    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render :show, status: :created, location: @point }
      else
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to points_url, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def generate_map_options
      {
        default_map_position:
          {
            coords:
              {
                latitude: 52.36132,
                longitude: 9.628606
              },
            default: true
          },
        infowindow_base_url: '',
        picture_base_url: '',
        default_zoom: 12
      }
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params[:point]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geopoints</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.haml
%h1 Listing points

%table
  %thead
    %tr
      %th Coordinates
      %th Address

  %tbody
    - @points.each do |point|
      %tr
        %td
          =# link_to 'Show', point
          =# link_to 'Edit', edit_point_path(point)
          =# link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' }
        %td=# point.coordinates
        %td=# point.address
%br

= link_to 'New Point', new_point_path

%h2 Map
%div{style:'width: 800px;'}
  %div{id:'map_container',style:'width: 800px; height: 400px;'}

%script{src:'//maps.google.com/maps/api/js?sensor=false&libraries=geometry'}
%script{src:'//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.1.2/src/markerclusterer_packed.js'}

:coffee
  jQuery ->
    init_map('map_container', #{raw @map_options}, #{raw @markers})
    #point_map.draw()

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>